#!/bin/bash

for num in 0 1
	do DEATH_STAR_ADDRESS=`ctool info death_star | grep -A2 "Node ${num}:" | grep "public ip:" | cut -d : -f2 | sed -e 's/^[ \t]*//'`,$DEATH_STAR_ADDRESS
done
DEATH_STAR_ADDRESS=$DEATH_STAR_ADDRESS`ctool info death_star | grep -A2 "Node 2:" | grep "public ip:" | cut -d : -f2 | sed -e 's/^[ \t]*//'`
ctool run yavin_4 0 'dse advrep edge conf --edge-id "yavin_4" --edge-id-col-name "edge_id" --hub-ip-addresses "'$DEATH_STAR_ADDRESS'"'
ctool run alderaan 0 'dse advrep edge conf --edge-id "alderaan" --edge-id-col-name "edge_id" --hub-ip-addresses "'$DEATH_STAR_ADDRESS'"'
ctool run yavin_4 0 'dse advrep edge channel create --keyspace yavin --table colonial_data --hub-keyspace galaxy --hub-table colonial_data --priority 1 --edge-id yavin --edge-id-col-name edge_id --enabled'
ctool run alderaan 0 'dse advrep edge channel create --keyspace alderaan --table colonial_data --hub-keyspace galaxy --hub-table colonial_data --priority 1 --edge-id alderaan --edge-id-col-name edge_id --enabled'

ctool run yavin_4 0 'dse advrep edge start'
ctool run alderaan 0 'dse advrep edge start'