#!/bin/bash
echo "Gathering death_star IP addresses for Advanced Replication configuration"
for num in 0 1 
	do DEATH_STAR_ADDRESS=`ctool info death_star | grep -A2 "Node ${num}:" | grep "public ip:" | cut -d : -f2 | sed -e 's/^[ \t]*//'`,$DEATH_STAR_ADDRESS
done
DEATH_STAR_ADDRESS=$DEATH_STAR_ADDRESS`ctool info death_star | grep -A2 "Node 2:" | grep "public ip:" | cut -d : -f2 | sed -e 's/^[ \t]*//'`
echo $DEATH_STAR_ADDRESS >> hub_addresses_for_advanced_replication
