#!/bin/bash

echo "Creating clusters for WTF project"
echo "Launching death_star cluster of 3 nodes"
ctool launch death_star 4 &
sleep 15
echo "Launching alderaan cluster of 1 node"
ctool launch -i c3.8xlarge alderaan 1 &
sleep 15
echo "Launching yavin_4 cluster of 1 node"
ctool launch -i c3.8xlarge yavin_4 1 &
wait
echo "All clusters launched"
echo "Installing DSE 5.0 on death_star cluster"
ctool install -a eap -v 5.0.0-eap7 -n 128 death_star enterprise &
echo "Installing DSE 5.0 on alderaan cluster"
ctool install -a eap -v 5.0.0-eap7 -n 128 alderaan enterprise &
echo "Installing DSE 5.0 on yavin_4 cluster"
ctool install -a eap -v 5.0.0-eap7 -n 128 yavin_4 enterprise &
wait
echo "DSE Installed on all clusters"
echo "Starting DSE on all clusters"
ctool start death_star enterprise &
ctool start alderaan enterprise &
ctool start yavin_4 enterprise &
wait
echo "DSE started on All clusters"

#INSERT ADD CLUSTER FOR OPSCENTER HERE

ctool scp alderaan 0 config/configure_dense_nodes /home/automaton
ctool scp yavin_4 0 config/configure_dense_nodes /home/automaton

echo "Setting up Multi-instance on alderaan cluster"
ctool run alderaan 0 './configure_dense_nodes' 
echo "Setting up Multi-instance on yavin_4 cluster"
ctool run yavin_4 0 './configure_dense_nodes'
echo "sleeping 30 seconds to allow configuration changes to take effect"
sleep 30

echo "Starting DSE and additional nodes on alderaan cluster"
ctool restart alderaan 0 enterprise
echo "Sleeping 60 seconds to allow restart to complete"
sleep 60
echo "Starting dse-alderaan_1"
ctool run alderaan 0 'sudo service dse-alderaan_1 start'
echo "Sleeping 5 minutes to allow dse-alderaan_1 to bootstrap fully"
sleep 300
echo "Starting dse-alderaan_2"
ctool run alderaan 0 'sudo service dse-alderaan_2 start'
echo "Sleeping 5 minutes to allow dse-alderaan_1 to bootstrap fully"
sleep 300
echo "Verifying all nodes in alderaan cluster are up and normal"
ctool run alderaan 0 'nodetool status'

echo "Starting DSE and additional nodes on yavin_4 cluster"
ctool restart yavin_4 0 enterprise
echo "Sleeping 60 seconds to allow restart to complete"
sleep 60
echo "Starting dse-yavin_4_1"
ctool run yavin_4 0 'sudo service dse-yavin_4_1 start'
echo "Sleeping 5 minutes to allow dse-yavin_4_1 to bootstrap fully"
sleep 300
echo "Starting dse-yavin_4_2"
ctool run yavin_4 0 'sudo service dse-yavin_4_2 start'
echo "Sleeping 5 minutes to allow dse-yavin_4_2 to bootstrap fully"
sleep 300
echo "Verifying all nodes in yavin_4 cluster are up and normal"
ctool run yavin_4 0 'nodetool status'

echo "Beginning schema work on yavin_4"
ctool scp yavin_4 0 config/configure_schema /home/automaton
ctool run yavin_4 0 './configure_schema'

echo "Beginning schema work on alderaan"
ctool scp alderaan 0 config/configure_schema /home/automaton
ctool run alderaan 0 './configure_schema'

echo "Sleeping for 1 hour to allow data popualation before initiating Advanced Replication"
#sleep 3600

#ed -i -e 's/foo/bar/g' filename

#script files on namek and tatooine should create dense node clusters using loopback addresses
# hub nodes should be using tiered storage
# namek and tatooine should replicate to hub
# namek should have issue with replication introduced - schema change fixed by a restart of the edge


